---

- name: Copy containerd.conf
  ansible.builtin.copy:
    src: modules-k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Modprobe command
  command: "{{item}}"
  loop:
    - modprobe overlay
    - modprobe br_netfilter

- name: Copy sys-k8s.conf
  ansible.builtin.copy:
    src: sys-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Systctl Apply
  command: "{{item}}"
  loop:
    - sysctl --system

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu   noble stable
    state: present
    filename:  docker

- name: Install ContainerD
  ansible.builtin.apt:
    name:
      - containerd.io
    state: present
    update_cache: true

- name: Create folder
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Copy config.toml
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml

- name: Start Containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
